# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(608, 668)
        dialog.setMinimumSize(QtCore.QSize(500, 500))
        dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grBx_ListView = QtWidgets.QGroupBox(self.centralwidget)
        self.grBx_ListView.setMinimumSize(QtCore.QSize(670, 140))
        self.grBx_ListView.setMaximumSize(QtCore.QSize(16777215, 140))
        self.grBx_ListView.setTitle("")
        self.grBx_ListView.setObjectName("grBx_ListView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grBx_ListView)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_cam1 = QtWidgets.QLabel(self.grBx_ListView)
        self.lbl_cam1.setMaximumSize(QtCore.QSize(50, 20))
        self.lbl_cam1.setObjectName("lbl_cam1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_cam1)
        self.listWidget_cam1 = QtWidgets.QListWidget(self.grBx_ListView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_cam1.sizePolicy().hasHeightForWidth())
        self.listWidget_cam1.setSizePolicy(sizePolicy)
        self.listWidget_cam1.setMinimumSize(QtCore.QSize(220, 100))
        self.listWidget_cam1.setMaximumSize(QtCore.QSize(220, 50))
        self.listWidget_cam1.setObjectName("listWidget_cam1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.listWidget_cam1)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_cam2 = QtWidgets.QLabel(self.grBx_ListView)
        self.lbl_cam2.setMaximumSize(QtCore.QSize(50, 20))
        self.lbl_cam2.setObjectName("lbl_cam2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_cam2)
        self.listWidget_cam2 = QtWidgets.QListWidget(self.grBx_ListView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_cam2.sizePolicy().hasHeightForWidth())
        self.listWidget_cam2.setSizePolicy(sizePolicy)
        self.listWidget_cam2.setMinimumSize(QtCore.QSize(220, 100))
        self.listWidget_cam2.setMaximumSize(QtCore.QSize(220, 50))
        self.listWidget_cam2.setObjectName("listWidget_cam2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.listWidget_cam2)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Step_Left = QtWidgets.QPushButton(self.grBx_ListView)
        self.pushButton_Step_Left.setEnabled(False)
        self.pushButton_Step_Left.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Left.setMaximumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Left.setStyleSheet("")
        self.pushButton_Step_Left.setObjectName("pushButton_Step_Left")
        self.horizontalLayout_2.addWidget(self.pushButton_Step_Left)
        self.pushButton_RunImgSeq = QtWidgets.QPushButton(self.grBx_ListView)
        self.pushButton_RunImgSeq.setEnabled(True)
        self.pushButton_RunImgSeq.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_RunImgSeq.setMaximumSize(QtCore.QSize(60, 25))
        self.pushButton_RunImgSeq.setStyleSheet("")
        self.pushButton_RunImgSeq.setObjectName("pushButton_RunImgSeq")
        self.horizontalLayout_2.addWidget(self.pushButton_RunImgSeq)
        self.pushButton_Step_Right = QtWidgets.QPushButton(self.grBx_ListView)
        self.pushButton_Step_Right.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Step_Right.sizePolicy().hasHeightForWidth())
        self.pushButton_Step_Right.setSizePolicy(sizePolicy)
        self.pushButton_Step_Right.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Right.setMaximumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Right.setStyleSheet("")
        self.pushButton_Step_Right.setObjectName("pushButton_Step_Right")
        self.horizontalLayout_2.addWidget(self.pushButton_Step_Right)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.grBx_ListView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_progress_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_progress_status.setMinimumSize(QtCore.QSize(500, 20))
        self.lbl_progress_status.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_progress_status.setObjectName("lbl_progress_status")
        self.horizontalLayout.addWidget(self.lbl_progress_status)
        self.lbl_info = QtWidgets.QLabel(self.centralwidget)
        self.lbl_info.setMinimumSize(QtCore.QSize(150, 20))
        self.lbl_info.setMaximumSize(QtCore.QSize(150, 20))
        self.lbl_info.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lbl_info.setAcceptDrops(False)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_info.setObjectName("lbl_info")
        self.horizontalLayout.addWidget(self.lbl_info)
        self.gridLayout_4.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.grBx_path = QtWidgets.QGroupBox(self.centralwidget)
        self.grBx_path.setMinimumSize(QtCore.QSize(670, 50))
        self.grBx_path.setMaximumSize(QtCore.QSize(16777215, 40))
        self.grBx_path.setTitle("")
        self.grBx_path.setObjectName("grBx_path")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grBx_path)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_browse = QtWidgets.QPushButton(self.grBx_path)
        self.pushButton_browse.setMaximumSize(QtCore.QSize(60, 20))
        self.pushButton_browse.setStyleSheet("")
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout_3.addWidget(self.pushButton_browse)
        self.lbl_in_directory = QtWidgets.QLabel(self.grBx_path)
        self.lbl_in_directory.setEnabled(True)
        self.lbl_in_directory.setMaximumSize(QtCore.QSize(120, 20))
        self.lbl_in_directory.setObjectName("lbl_in_directory")
        self.horizontalLayout_3.addWidget(self.lbl_in_directory)
        self.lineEdit = QtWidgets.QLineEdit(self.grBx_path)
        self.lineEdit.setMinimumSize(QtCore.QSize(400, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setBaseSize(QtCore.QSize(1000, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_close = QtWidgets.QPushButton(self.grBx_path)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(60, 20))
        self.pushButton_close.setMaximumSize(QtCore.QSize(60, 20))
        self.pushButton_close.setStyleSheet("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.grBx_path, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_JPG_COLORMAP_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_COLORMAP_1.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_COLORMAP_1.setSizePolicy(sizePolicy)
        self.lbl_JPG_COLORMAP_1.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_COLORMAP_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_JPG_COLORMAP_1.setText("")
        self.lbl_JPG_COLORMAP_1.setObjectName("lbl_JPG_COLORMAP_1")
        self.gridLayout.addWidget(self.lbl_JPG_COLORMAP_1, 0, 1, 1, 1)
        self.lbl_JPG_img_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_img_3.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_img_3.setSizePolicy(sizePolicy)
        self.lbl_JPG_img_3.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_img_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_JPG_img_3.setText("")
        self.lbl_JPG_img_3.setObjectName("lbl_JPG_img_3")
        self.gridLayout.addWidget(self.lbl_JPG_img_3, 2, 0, 1, 1)
        self.lbl_JPG_img_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_img_1.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_img_1.setSizePolicy(sizePolicy)
        self.lbl_JPG_img_1.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_img_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_JPG_img_1.setText("")
        self.lbl_JPG_img_1.setObjectName("lbl_JPG_img_1")
        self.gridLayout.addWidget(self.lbl_JPG_img_1, 0, 0, 1, 1)
        self.lbl_JPG_img_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_img_2.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_img_2.setSizePolicy(sizePolicy)
        self.lbl_JPG_img_2.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_img_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_JPG_img_2.setText("")
        self.lbl_JPG_img_2.setObjectName("lbl_JPG_img_2")
        self.gridLayout.addWidget(self.lbl_JPG_img_2, 1, 0, 1, 1)
        self.lbl_JPG_COLORMAP_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_COLORMAP_2.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_COLORMAP_2.setSizePolicy(sizePolicy)
        self.lbl_JPG_COLORMAP_2.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_COLORMAP_2.setText("")
        self.lbl_JPG_COLORMAP_2.setObjectName("lbl_JPG_COLORMAP_2")
        self.gridLayout.addWidget(self.lbl_JPG_COLORMAP_2, 1, 1, 1, 1)
        self.lbl_JPG_COLORMAP_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_COLORMAP_3.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_COLORMAP_3.setSizePolicy(sizePolicy)
        self.lbl_JPG_COLORMAP_3.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_COLORMAP_3.setText("")
        self.lbl_JPG_COLORMAP_3.setObjectName("lbl_JPG_COLORMAP_3")
        self.gridLayout.addWidget(self.lbl_JPG_COLORMAP_3, 2, 1, 1, 1)
        self.lbl_JPG_RGB_HIST_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_RGB_HIST_1.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_RGB_HIST_1.setSizePolicy(sizePolicy)
        self.lbl_JPG_RGB_HIST_1.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_RGB_HIST_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_JPG_RGB_HIST_1.setText("")
        self.lbl_JPG_RGB_HIST_1.setObjectName("lbl_JPG_RGB_HIST_1")
        self.gridLayout.addWidget(self.lbl_JPG_RGB_HIST_1, 0, 2, 1, 1)
        self.lbl_JPG_RGB_HIST_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_RGB_HIST_2.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_RGB_HIST_2.setSizePolicy(sizePolicy)
        self.lbl_JPG_RGB_HIST_2.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_RGB_HIST_2.setText("")
        self.lbl_JPG_RGB_HIST_2.setObjectName("lbl_JPG_RGB_HIST_2")
        self.gridLayout.addWidget(self.lbl_JPG_RGB_HIST_2, 1, 2, 1, 1)
        self.lbl_JPG_RGB_HIST_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_JPG_RGB_HIST_3.sizePolicy().hasHeightForWidth())
        self.lbl_JPG_RGB_HIST_3.setSizePolicy(sizePolicy)
        self.lbl_JPG_RGB_HIST_3.setMinimumSize(QtCore.QSize(220, 220))
        self.lbl_JPG_RGB_HIST_3.setText("")
        self.lbl_JPG_RGB_HIST_3.setObjectName("lbl_JPG_RGB_HIST_3")
        self.gridLayout.addWidget(self.lbl_JPG_RGB_HIST_3, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)
        dialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dialog)
        self.statusbar.setObjectName("statusbar")
        dialog.setStatusBar(self.statusbar)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Image Analysis"))
        self.lbl_cam1.setText(_translate("dialog", "Camera 1:"))
        self.lbl_cam2.setText(_translate("dialog", "Camera 2:"))
        self.pushButton_Step_Left.setToolTip(_translate("dialog", "Starts or stopps the image slide show."))
        self.pushButton_Step_Left.setText(_translate("dialog", "<<"))
        self.pushButton_RunImgSeq.setToolTip(_translate("dialog", "Starts or stopps the image slide show."))
        self.pushButton_RunImgSeq.setText(_translate("dialog", "Run"))
        self.pushButton_Step_Right.setText(_translate("dialog", ">>"))
        self.lbl_progress_status.setText(_translate("dialog", "---"))
        self.lbl_info.setText(_translate("dialog", "Info:"))
        self.pushButton_browse.setText(_translate("dialog", "Browse"))
        self.lbl_in_directory.setText(_translate("dialog", " Root Image Path:"))
        self.lineEdit.setToolTip(_translate("dialog", "Enter path to image directory."))
        self.pushButton_close.setText(_translate("dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QMainWindow()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())

